postgresql: &postgresql
  adapter: postgresql
  database: betterbet_<%= Rails.env %>
  min_messages: ERROR

defaults: &defaults
  host: localhost
  <<: *<%= ENV['DB'] || "postgresql" %>

test:
  <<: *defaults